#!/usr/bin/env python
#
# ReGrowl Server
# A simple ? server for *regrowling* GNTP messages to the local OSX Growl system

import SocketServer
import traceback
import logging

import gntp_bridge as gntp


class GNTPServer(SocketServer.TCPServer):
	def __init__(self, options, RequestHandlerClass):
		try:
			SocketServer.TCPServer.__init__(self, (options.host, options.port), RequestHandlerClass)
		except:
			logging.getLogger('Server').critical('There is already a server running on port %d'%options.port)
			exit(1)
		self.options = options
		logging.getLogger('Server').info('Activating server')
	def run(self):
		sa = self.socket.getsockname()
		logging.getLogger('Server').info('Listening for GNTP on %s port %s'%(sa[0],sa[1]))
		self.serve_forever()

class GNTPHandler(SocketServer.StreamRequestHandler):
	def read(self):
		bufferLength = 2048
		buffer = ''
		while(1):
			data = self.request.recv(bufferLength)
			logging.getLogger('Server').info('Reading %s Bytes',len(data))
			buffer = buffer + data
			if len(data) < bufferLength and buffer.endswith('\r\n\r\n'):
				break
		logging.getLogger('Server').debug(buffer)
		return buffer
	def write(self,msg):
		logging.getLogger('Server').debug(msg)
		self.request.sendall(msg)
	def handle(self):
		reload(gntp)
		self.data = self.read()
		
		try:
			message = gntp.parse_gntp(self.data,self.server.options.password)
			
			response = gntp.GNTPOK(action=message.info['messagetype'])
			if message.info['messagetype'] == 'NOTICE':
				response.add_header('Notification-ID','')
			elif message.info['messagetype'] == 'SUBSCRIBE':
				raise gntp.UnsupportedError()
				#response.add_header('Subscription-TTL','10')
			self.write(response.encode())
		except gntp.BaseError, e:
			if self.server.growl_debug:
				traceback.print_exc()
			if e.gntp_error:
				self.write(e.gntp_error())
		except:
			error = gntp.GNTPError(errorcode=500,errordesc='Unknown server error')
			self.write(error.encode())
			raise
		
		message.send()
		
if __name__ == "__main__":
	from Parser import ServerParser
	
	(options,args) = ServerParser().parse_args()
		
	logging.basicConfig(
		level=(logging.DEBUG if options.debug else logging.INFO),
		format='%(name)-12s: %(levelname)-8s %(message)s')
	
	server = GNTPServer(options, GNTPHandler)
	server.run()
